=== AuDigitalHealth/mhr-b2b-client-dotnet/wsdls/schema/External/View/PCEHR_HealthRecordOverview_Response.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--Baseline version issued 14 April 2015-->
<xs:schema xmlns="http://ns.electronichealth.net.au/pcehr/xsd/interfaces/HealthRecordOverview/1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:q3="http://ns.electronichealth.net.au/pcehr/xsd/interfaces/b2b/1.0" xmlns:ns1="http://ns.electronichealth.net.au/pcehr/xsd/common/CommonCoreElements/1.0" xmlns:ns2="http://ns.electronichealth.net.au/pcehr/xsd/view/ViewCommonType/1.0" targetNamespace="http://ns.electronichealth.net.au/pcehr/xsd/interfaces/HealthRecordOverview/1.0" elementFormDefault="qualified">
	<xs:import namespace="http://ns.electronichealth.net.au/pcehr/xsd/common/CommonCoreElements/1.0" schemaLocation="../../Common/PCEHR_CommonTypes_Supplementary.xsd"/>
	<xs:import namespace="http://ns.electronichealth.net.au/pcehr/xsd/view/ViewCommonType/1.0" schemaLocation="PCEHR_View_CommonType.xsd"/>
	<xs:element name="healthRecordOverviewResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="viewMetadata">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="individualProfile">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="ns1:ihiNumber"/>
										<xs:element name="individual" type="ns1:individualTypeSupp"/>
										<xs:element name="indigenousStatus" type="xs:string" minOccurs="0"/>
										<xs:element name="veteranAndADFStatus" type="xs:string" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="viewParameters">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="clinicalSynopsisLength" type="xs:int"/>
										<xs:element name="viewVersionNumber" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="newDocuments">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="informationAvailable" type="xs:boolean"/>
							<xs:element name="document" type="ns2:documentDT" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="sharedHealthSummary">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="informationAvailable" type="xs:boolean"/>
							<xs:element name="sharedHealthSummaryAtomicData" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="documentDate" type="xs:string"/>
										<xs:element name="cdaDocumentTitle" type="xs:string"/>
										<xs:element name="shsAuthorName" type="ns2:nameTypeDT"/>
										<xs:element name="shsAuthorId" type="xs:string"/>
										<xs:element name="shsAuthorDesignation" type="ns2:CodedType"/>
										<xs:element name="shsAuthorOrgName" type="xs:string"/>
										<xs:element name="shsAuthorOrgId">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="16"/>
													<xs:maxLength value="16"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="shsAuthorOrgAddress" type="ns2:addressTypeDT" minOccurs="0"/>
										<xs:element name="shsAuthorOrgContactDetails" type="ns2:contactDetailsDT" minOccurs="0" maxOccurs="unbounded"/>
										<xs:element name="shsAuthorAddress" type="ns2:addressTypeDT" minOccurs="0"/>
										<xs:element name="shsAuthorContactDetails" type="ns2:contactDetailsDT" minOccurs="0" maxOccurs="unbounded"/>
										<xs:element name="shsEntitlements" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="entitlement" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="entitlementNumberId" type="xs:string"/>
																<xs:element name="entitlementType" type="ns2:CodedType"/>
																<xs:element name="entitlementEffectiveTime" type="ns2:timeStampDT" minOccurs="0"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="shsAuthorQualifications" type="ns2:CodedType" minOccurs="0"/>
										<xs:element name="medicinesList">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="informationAvailable" type="ns2:informationAvailableDT"/>
													<xs:element name="medicine" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="medicineTitle" type="ns2:CodedType"/>
																<xs:element name="medicineDose" type="xs:string"/>
																<xs:element name="medicineDesc" minOccurs="0" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="indication" type="xs:string" minOccurs="0"/>
																			<xs:element name="comment" type="xs:string" minOccurs="0"/>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="advReactionsList">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="informationAvailable" type="ns2:informationAvailableDT"/>
													<xs:element name="advReaction" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="advReactionCause" type="ns2:CodedType"/>
																<xs:element name="advReactionManifestation" type="ns2:CodedType" minOccurs="0" maxOccurs="unbounded"/>
																<xs:element name="advReactionType" type="ns2:CodedType" minOccurs="0"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="immunisationList">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="informationAvailable" type="ns2:informationAvailableDT"/>
													<xs:element name="immunisation" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="immunisationDate" type="ns2:timeStampDT"/>
																<xs:element name="immunisationTitle" type="ns2:CodedType"/>
																<xs:element name="immunisationSequenceNumber" type="xs:int" minOccurs="0"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="medHistoryList">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="informationAvailable" type="ns2:informationAvailableDT" minOccurs="3" maxOccurs="3"/>
													<xs:element name="problemAndDiagnosis" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="medTitle" type="ns2:CodedType"/>
																<xs:element name="medDateO" type="ns2:timeStampDT" minOccurs="0"/>
																<xs:element name="medDateR" type="ns2:timeStampDT" minOccurs="0"/>
																<xs:element name="medComment" type="xs:string" minOccurs="0"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="procedure" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="medTitle" type="ns2:CodedType"/>
																<xs:element name="medDateO" type="ns2:timeStampDT" minOccurs="0"/>
																<xs:element name="medDateR" type="ns2:timeStampDT" minOccurs="0"/>
																<xs:element name="medComment" type="xs:string" minOccurs="0"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="otherMedicalHistory" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="medTitle" type="ns2:CodedType"/>
																<xs:element name="medDateO" type="ns2:timeStampDT" minOccurs="0"/>
																<xs:element name="medDateR" type="ns2:timeStampDT" minOccurs="0"/>
																<xs:element name="medComment" type="xs:string" minOccurs="0"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="otherLinks">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="link" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="linkName" type="xs:string"/>
										<xs:element name="linkTitle" type="xs:string"/>
										<xs:element name="linkTarget" type="xs:anyURI" minOccurs="0"/>
										<xs:element name="informationAvailable" type="xs:boolean"/>
										<xs:element name="linkType">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="Document"/>
													<xs:enumeration value="View"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="recentDocuments">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="informationAvailable" type="xs:boolean"/>
							<xs:element name="document" type="ns2:documentDT" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== AuDigitalHealth/mhr-b2b-client-dotnet/wsdls/schema/External/View/Mappings/HRO 20141003_min_v0 5.xml
<?xml version="1.0" encoding="UTF-8"?>
<healthRecordOverviewResponse xsi:schemaLocation="http://ns.electronichealth.net.au/pcehr/xsd/interfaces/HealthRecordOverview/1.0 file:///C:/Users/daniel.kesuma/Desktop/PCEHR_Schemas-20140701_v1.5.1/PCEHR_Schemas-20140701/schema/External/View/PCEHR_HealthRecordOverview_Response.xsd" xmlns="http://ns.electronichealth.net.au/pcehr/xsd/interfaces/HealthRecordOverview/1.0" xmlns:ns1="http://ns.electronichealth.net.au/pcehr/xsd/common/CommonCoreElements/1.0" xmlns:ns2="http://ns.electronichealth.net.au/pcehr/xsd/view/ViewCommonType/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<viewMetadata>
		<individualProfile>
			<ns1:ihiNumber>8003604567901466</ns1:ihiNumber>
			<individual>
				<ns1:name>
					<ns1:nameTitle>MR</ns1:nameTitle>
					<ns1:familyName>DIMITRY</ns1:familyName>
					<ns1:givenName>PERCY SOLOMON</ns1:givenName>
					<ns1:nameSuffix>D</ns1:nameSuffix>
				</ns1:name>
				<ns1:sex>M</ns1:sex>
				<ns1:dateOfBirth>1967-08-13</ns1:dateOfBirth>
			</individual>
			<indigenousStatus>9</indigenousStatus>
			<veteranAndADFStatus>9</veteranAndADFStatus>					
		</individualProfile>
		<viewParameters>
		<viewVersionNumber>1.0</viewVersionNumber>
			<clinicalSynopsisLength>0</clinicalSynopsisLength>
		</viewParameters>
	</viewMetadata>
	<newDocuments>
		<informationAvailable>false</informationAvailable>
	</newDocuments>
	<sharedHealthSummary>
		<informationAvailable>false</informationAvailable>
	</sharedHealthSummary>
	<otherLinks>
		<link>
			<linkName>MedicareOverview</linkName>
			<linkTitle>Medicare Overview</linkTitle>
			<linkTarget>MedicareOverview</linkTarget>
			<informationAvailable>false</informationAvailable>
			<linkType>View</linkType>
		</link>
		<link>
			<linkName>DiagnosticImagingView</linkName>
			<linkTitle>Diagnostic Imaging View</linkTitle>
			<linkTarget>DiagnosticImagingView</linkTarget>
			<informationAvailable>false</informationAvailable>
			<linkType>View</linkType>
		</link>
		<link>
			<linkName>PathologyIndexView</linkName>
			<linkTitle>Pathology Index View</linkTitle>
			<linkTarget>PathologyIndexView</linkTarget>
			<informationAvailable>false</informationAvailable>
			<linkType>View</linkType>
		</link>
		<link>
			<linkName>HealthCheckAssessmentView</linkName>
			<linkTitle>Health Check Assessment View</linkTitle>
			<linkTarget>HealthCheckAssessmentView</linkTarget>
			<informationAvailable>false</informationAvailable>
			<linkType>View</linkType>
		</link>
		<link>
			<linkName>PrescriptionAndDispenseView</linkName>
			<linkTitle>Prescription and Dispense View</linkTitle>
			<linkTarget>PrescriptionAndDispenseView</linkTarget>
			<informationAvailable>false</informationAvailable>
			<linkType>View</linkType>
		</link>
		<link>
			<linkName>PersonalHealthSummary</linkName>
			<linkTitle>Personal Health Summary</linkTitle>
			<linkTarget/>
			<informationAvailable>false</informationAvailable>
			<linkType>Document</linkType>
		</link>
		<link>
			<linkName>AdvanceCareDirective</linkName>
			<linkTitle>Advance Care Directive</linkTitle>
			<linkTarget/>
			<informationAvailable>false</informationAvailable>
			<linkType>Document</linkType>
		</link>
	</otherLinks>
	<recentDocuments>
		<informationAvailable>false</informationAvailable>
	</recentDocuments>
</healthRecordOverviewResponse>
